all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    APP_VERSION: "{{ APP_VERSION | default('1.0.0') }}"   # will be overridden from GitHub Actions
    image_api: "{{ AWS_ACCOUNT }}.dkr.ecr.us-east-1.amazonaws.com/api:{{ APP_VERSION }}"
    image_worker: "{{ AWS_ACCOUNT }}.dkr.ecr.us-east-1.amazonaws.com/worker:{{ APP_VERSION }}"
    image_frontend: "{{ AWS_ACCOUNT }}.dkr.ecr.us-east-1.amazonaws.com/frontend::{{ APP_VERSION }}"
    apps:
      - name: api
        namespace: myapp
        image: "{{ image_api }}"
        replicas: 2
      - name: worker
        namespace: myapp
        image: "{{ image_worker }}"
        replicas: 1
      - name: frontend
        namespace: myapp
        image: "{{ image_frontend }}"
        replicas: 2
