all:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    image_api: "{{ AWS_ACCOUNT }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/api"
    image_worker: "{{ AWS_ACCOUNT }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/worker"
    image_frontend: "{{ AWS_ACCOUNT }}.dkr.ecr.{{ AWS_REGION }}.amazonaws.com/frontend"
    environment: qa
    apps:
      - name: api
        namespace: qa
        image: "{{ image_api }}"
        replicas: 2
        container_port: 8080
        service_port: 80
        service_type: ClusterIP

      - name: worker
        namespace: qa
        image: "{{ image_worker }}"
        replicas: 1
        container_port: 8081
        service_port: 8081
        service_type: ClusterIP

      - name: frontend
        namespace: qa
        image: "{{ image_frontend }}"
        replicas: 2
        container_port: 80
        service_port: 80
        service_type: LoadBalancer