apps:
  - name: api
    namespace: myapp
    image: "{{ image_api }}"
    replicas: 2
  - name: worker
    namespace: myapp
    image: "{{ image_worker }}"
    replicas: 1
  - name: frontend
    namespace: myapp
    image: "{{ image_frontend }}"
    replicas: 2