name: CI/CD Pipeline

on:
  push:
    # branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to push"
        required: true
        type: string

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    # env:
    #   APP_VERSION: ${GITHUB_REF#refs/tags/v}

    steps:
      - uses: actions/checkout@v4

    #   - name: Set version
    #     run: echo "APP_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    #   - name: Extract version
    #     id: version
    #     run: |
    #         VERSION="${GITHUB_REF#refs/tags/v}"
    #         echo "version=$VERSION" >> $GITHUB_OUTPUT
    #         echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set APP_VERSION
        id: set-version
        run: |
            if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.image_tag }}"
            elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/v}"
            else
            # fallback to branch name or default
            VERSION="${GITHUB_REF#refs/heads/}"
            fi

            echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
            echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Debug version
        run: echo "APP_VERSION=$APP_VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      ########################################
      # API SERVICE
      ########################################
      - name: Debug registry
        run: |
            echo "Registry value: '${{ steps.login-ecr.outputs.registry }}'"
            
      - name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./application/api/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/api:${{ env.APP_VERSION }}
            ${{ steps.login-ecr.outputs.registry }}/api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      ########################################
      # WORKER SERVICE
      ########################################
      - name: Build and push Worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./application/worker/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/worker:${{ env.APP_VERSION }}
            ${{ steps.login-ecr.outputs.registry }}/worker:latest

          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      ########################################
      # FRONTEND SERVICE
      ########################################
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./application/frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/frontend:${{ env.APP_VERSION }}
            ${{ steps.login-ecr.outputs.registry }}/frontend:latest

          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  deploy-qa:
    needs: build-push
    runs-on: ubuntu-latest
    environment: qa
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Deploy to QA
        run: echo "Deploying version ${{ env.APP_VERSION }} to QA environment..."

      - uses: actions/checkout@v4
    
      - name: Install OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 'latest' # Or a specific version, e.g., '4.11'

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true # Adjust this based on your cluster's certificate setup
        #   namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
    
      - name: Testing step
        run: |
            oc whoami --show-server

      - name: Set up Python dependencies
        run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install ansible kubernetes openshift

      - name: Deploy via Ansible
        run: |
          cd application/ansible
          ansible-playbook playbooks/deploy-app.yml -i inventories/qa/hosts.yml \
            -e "APP_VERSION=${{ env.APP_VERSION }}" \
            -e "AWS_ACCOUNT=${{ secrets.AWS_ACCOUNT }}" \
            -e "AWS_REGION=${{ secrets.AWS_REGION }}"


  deploy-uat:
    needs: deploy-qa
    runs-on: ubuntu-latest
    environment: uat
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Deploy to UAT
        run: echo "Deploying version ${{ env.APP_VERSION }} to QA environment..."

  deploy-prod:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Deploy to QA
        run: echo "Deploying version ${{ env.APP_VERSION }} to QA environment..."